# BUILDER
FROM --platform=$BUILDPLATFORM oven/bun:latest AS builder
WORKDIR /app
COPY . .
RUN bun ci && bun run compile

# ------------------------------------------

# RUNNER
FROM imbios/bun-node:23-slim AS runner

# Install base tools
RUN apt-get update && apt-get install -y unzip tmux curl wget gpg git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Environment Variables
ENV JARVIS_SERVER_PORT=4202

# Expose ports
EXPOSE 4202

# Copy the built application
COPY --from=builder /app/output/dist /agent-jarvis

WORKDIR /agent-jarvis

CMD ["bun", "jarvis.js"]